version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/tomcat/webapps

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:


  BeforeInstall:
    - location: uninstall_war_file.sh
      timeout: 300
      runas: ec2-user


