version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/tomcat/webapps

permissions:
  - object: /
    pattern: 777
    owner: ec2-user
    group: ec2-user

hooks:
  Application Stop:
    - location: /usr/local/tomcat/webapps/stop_application.sh
      timeout: 300
      runas: ec2-user

  BeforeInstall:
    - location: /usr/local/tomcat/webapps/uninstall_war_file.sh
      timeout: 300
      runas: ec2-user

  Application Start:
    - location: /usr/local/tomcat/webapps/start_application.sh
      timeout: 300
      runas: ec2-user
