version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/tomcat/webapps

permissions:
  - object: /
    pattern: 777
    owner: ec2-user
    group: ec2-user

hooks:
  Application Stop:
    - location: stop_application.sh
      timeout: 600
      runas: ec2-user

  BeforeInstall:
    - location: uninstall_war_file.sh
      timeout: 600
      runas: ec2-user

  Application Start:
    - location: start_application.sh
      timeout: 600
      runas: ec2-user
